// Types Barrel Export - Export all types from the types directory

// User Types
export type {
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  UserProfile,
  UserState,
  AuthState,
  UserSettings,
  UserStats,
  UserAchievementProgress,
  LearningGoal,
  UserActivity,
} from './user';

// Character Types
export type {
  Character,
  CharacterType,
  CharacterDifficulty,
  CharacterMastery,
  LearningSession,
  CharacterState,
  CharacterSet,
  CharacterFrequency,
  CharacterSimilarity,
  CharacterLearningProgress,
  CharacterPracticeSession,
  Stroke,
  CharacterRecognitionResult,
  CharacterLearningMetrics,
  CharacterStudyGroup,
  CharacterChallenge,
} from './character';

// Progress Types
export type {
  Achievement,
  LeaderboardEntry,
  ProgressStats,
  ProgressState,
  XPTransaction,
  Level,
  StreakData,
  DailyProgress,
  WeeklyProgress,
  MonthlyProgress,
  ProgressAnalytics,
  ProgressGoal,
  ProgressMilestone,
  ProgressComparison,
  ProgressReport,
} from './progress';

// API Types
export type {
  ApiResponse,
  PaginationParams,
  PaginatedResponse,
  AuthLoginRequest,
  AuthLoginResponse,
  AuthRegisterRequest,
  AuthRegisterResponse,
  AuthRefreshRequest,
  AuthRefreshResponse,
  AuthForgotPasswordRequest,
  AuthResetPasswordRequest,
  AuthVerifyEmailRequest,
  UserProfileResponse,
  UserUpdateProfileRequest,
  UserSettingsResponse,
  CharacterResponse,
  CharactersListRequest,
  CharactersListResponse,
  VocabularyResponse,
  LessonResponse,
  ProgressStatsResponse,
  ProgressAddXPRequest,
  ProgressAddXPResponse,
  AchievementResponse,
  LeaderboardResponse,
  DiscussionResponse,
  PostResponse,
  CommentResponse,
  StudyGroupResponse,
  NotificationResponse,
  NotificationPreferencesResponse,
  NotificationPreferencesRequest,
  AnalyticsEventRequest,
  AnalyticsMetricsResponse,
  AnalyticsReportResponse,
  ApiError,
  ValidationError,
  ApiErrorResponse,
} from './api';

// OCR Types
export type {
  OCRConfig,
  OCRResult,
  CanvasPoint,
  CanvasStroke,
  CanvasDrawing,
  DrawingRecognition,
  StrokeAnalysis,
  CharacterRecognition,
  OCRProcessing,
  DrawingSession,
  DrawingFeedback,
  DrawingAnalytics,
  DrawingComparison,
  DrawingPractice,
  DrawingChallenge,
  DrawingRecognitionModel,
  DrawingDataExport,
  DrawingImport,
} from './ocr';

// UI Types
export type {
  ToastType,
  Toast,
  ToastData,
  Modal,
  UIState,
  ValidationRule,
  ValidationResult,
  FormState,
  NavigationItem,
  BreadcrumbItem,
  LayoutConfig,
  ThemeConfig,
  AnimationConfig,
  BreakpointConfig,
  AccessibilityConfig,
  PerformanceMetrics,
  UIError,
  LoadingState,
  Notification,
} from './ui';

// Community Types
export type {
  StudyGroup,
  StudyGroupMembership,
  Discussion,
  DiscussionCreateRequest,
  Post,
  PostCreateRequest,
  Comment,
  CommentCreateRequest,
  UserConnection,
  CommunityState,
  StudyGroupCreateRequest,
  CommunityCategory,
  ModerationAction,
  CommunityAnalytics,
  CommunityNotification,
  CommunityLeaderboard,
  CommunityReport,
} from './community';